### ISSUE TITLE
Can't install TBtools in Mac

### ISSUE THREAD

**Issue by sgbataller** [CJ-Chen/TBtools#30]
“TBtools Installer” can’t be opened because Apple cannot check it for malicious software.

**Comment by CJ-Chen** [comment]
自己想想办法，这类警告太常见了。百度或者谷歌一下。



发自我的iPhone


------------------ Original ------------------
From: sgbataller ***@***.***&gt;
Date: Tue,Feb 1,2022 2:30 AM
To: CJ-Chen/TBtools ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [CJ-Chen/TBtools] Can't install TBtools in Mac (Issue #30)





 
“TBtools Installer” can’t be opened because Apple cannot check it for malicious software.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tondehwarr** [comment]
can't install TBtools on mac, saying software expire
